-- Aegis-Demo 테넌트 완전한 샘플 데이터
-- models, bom, pricing, main_materials, sub_materials, inventory

-- 1. 주요 자재 (Main Materials) 삽입
INSERT INTO ptop.main_materials (tenant_id, product_name, standard, unit_length_m, unit_price) VALUES ('demo', 'HGI PIPE 50mm', '50x50x1.6', '6.0', 45000);
INSERT INTO ptop.main_materials (tenant_id, product_name, standard, unit_length_m, unit_price) VALUES ('demo', 'HGI PIPE 75mm', '75x75x2.3', '6.0', 68000);
INSERT INTO ptop.main_materials (tenant_id, product_name, standard, unit_length_m, unit_price) VALUES ('demo', 'ANGLE STEEL 50mm', '50x50x5', '6.0', 52000);
INSERT INTO ptop.main_materials (tenant_id, product_name, standard, unit_length_m, unit_price) VALUES ('demo', 'STEEL PLATE 10mm', '1000x2000x10', '1.0', 85000);
INSERT INTO ptop.main_materials (tenant_id, product_name, standard, unit_length_m, unit_price) VALUES ('demo', 'AL PROFILE', '40x40x2', '6.0', 38000);
INSERT INTO ptop.main_materials (tenant_id, product_name, standard, unit_length_m, unit_price) VALUES ('demo', 'BOLT M16', 'M16x50', '1.0', 2500);

-- 2. 보조 자재 (Sub Materials) 삽입
INSERT INTO ptop.sub_materials (tenant_id, product_name, unit, unit_price) VALUES ('demo', '용접', 'EA', 5000);
INSERT INTO ptop.sub_materials (tenant_id, product_name, unit, unit_price) VALUES ('demo', '페인트', 'L', 15000);
INSERT INTO ptop.sub_materials (tenant_id, product_name, unit, unit_price) VALUES ('demo', '너트 M16', 'EA', 800);
INSERT INTO ptop.sub_materials (tenant_id, product_name, unit, unit_price) VALUES ('demo', '와셔', 'EA', 500);
INSERT INTO ptop.sub_materials (tenant_id, product_name, unit, unit_price) VALUES ('demo', '콘크리트 기초', 'EA', 25000);

-- 3. 재고 (Inventory) 초기화
INSERT INTO ptop.inventory (tenant_id, item_id, product_name, standard, unit_price, current_quantity, unit) VALUES ('demo', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 45000, 100, 'EA');
INSERT INTO ptop.inventory (tenant_id, item_id, product_name, standard, unit_price, current_quantity, unit) VALUES ('demo', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 45000, 100, 'EA');
INSERT INTO ptop.inventory (tenant_id, item_id, product_name, standard, unit_price, current_quantity, unit) VALUES ('demo', 'MM-ANGLE-50', 'ANGLE STEEL 50mm', '50x50x5', 45000, 100, 'EA');
INSERT INTO ptop.inventory (tenant_id, item_id, product_name, standard, unit_price, current_quantity, unit) VALUES ('demo', 'MM-PLATE-10', 'STEEL PLATE 10mm', '1000x2000x10', 45000, 100, 'EA');
INSERT INTO ptop.inventory (tenant_id, item_id, product_name, standard, unit_price, current_quantity, unit) VALUES ('demo', 'MM-AL-PROF', 'AL PROFILE', '40x40x2', 45000, 100, 'EA');
INSERT INTO ptop.inventory (tenant_id, item_id, product_name, standard, unit_price, current_quantity, unit) VALUES ('demo', 'MM-BOLT-M16', 'BOLT M16', 'M16x50', 45000, 100, 'EA');

-- 4. 모델 (Models) 삽입
-- 디자인형울타리 모델
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'DESIGN_FENCE_001', '디자인형울타리-기본형 1000H', '디자인형울타리', '1000x2000mm', 'QT-2025-DF001', '디자인형울타리-기본형 1000H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'DESIGN_FENCE_002', '디자인형울타리-라운드톱 1200H', '디자인형울타리', '1200x2000mm', 'QT-2025-DF002', '디자인형울타리-라운드톱 1200H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'DESIGN_FENCE_003', '디자인형울타리-모던형 1000H', '디자인형울타리', '1000x2000mm', 'QT-2025-DF003', '디자인형울타리-모던형 1000H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'DESIGN_FENCE_004', '디자인형울타리-곡선형 1100H', '디자인형울타리', '1100x2000mm', 'QT-2025-DF004', '디자인형울타리-곡선형 1100H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'DESIGN_FENCE_005', '디자인형울타리-기하학형 1050H', '디자인형울타리', '1050x2000mm', 'QT-2025-DF005', '디자인형울타리-기하학형 1050H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'DESIGN_FENCE_006', '디자인형울타리-스트라이프 1000H', '디자인형울타리', '1000x2000mm', 'QT-2025-DF006', '디자인형울타리-스트라이프 1000H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'DESIGN_FENCE_007', '디자인형울타리-대각선 1150H', '디자인형울타리', '1150x2000mm', 'QT-2025-DF007', '디자인형울타리-대각선 1150H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'DESIGN_FENCE_008', '디자인형울타리-프레임형 1000H', '디자인형울타리', '1000x2000mm', 'QT-2025-DF008', '디자인형울타리-프레임형 1000H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'DESIGN_FENCE_009', '디자인형울타리-나무결 1200H', '디자인형울타리', '1200x2000mm', 'QT-2025-DF009', '디자인형울타리-나무결 1200H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'DESIGN_FENCE_010', '디자인형울타리-미니멀 900H', '디자인형울타리', '900x2000mm', 'QT-2025-DF010', '디자인형울타리-미니멀 900H 시리즈');

-- 금속재기타울타리 모델
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'METAL_FENCE_001', '금속재기타울타리-앵글형 1000H', '금속재기타울타리', '1000x2000mm', 'QT-2025-MF001', '금속재기타울타리-앵글형 1000H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'METAL_FENCE_002', '금속재기타울타리-파이프형 1200H', '금속재기타울타리', '1200x2000mm', 'QT-2025-MF002', '금속재기타울타리-파이프형 1200H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'METAL_FENCE_003', '금속재기타울타리-체인링크 1000H', '금속재기타울타리', '1000x2000mm', 'QT-2025-MF003', '금속재기타울타리-체인링크 1000H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'METAL_FENCE_004', '금속재기타울타리-메쉬형 1100H', '금속재기타울타리', '1100x2000mm', 'QT-2025-MF004', '금속재기타울타리-메쉬형 1100H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'METAL_FENCE_005', '금속재기타울타리-박스빔 1150H', '금속재기타울타리', '1150x2000mm', 'QT-2025-MF005', '금속재기타울타리-박스빔 1150H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'METAL_FENCE_006', '금속재기타울타리-철봉격자 1050H', '금속재기타울타리', '1050x2000mm', 'QT-2025-MF006', '금속재기타울타리-철봉격자 1050H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'METAL_FENCE_007', '금속재기타울타리-스틸플레이트 1000H', '금속재기타울타리', '1000x2000mm', 'QT-2025-MF007', '금속재기타울타리-스틸플레이트 1000H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'METAL_FENCE_008', '금속재기타울타리-구조강재 1200H', '금속재기타울타리', '1200x2000mm', 'QT-2025-MF008', '금속재기타울타리-구조강재 1200H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'METAL_FENCE_009', '금속재기타울타리-갈바강판 1100H', '금속재기타울타리', '1100x2000mm', 'QT-2025-MF009', '금속재기타울타리-갈바강판 1100H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'METAL_FENCE_010', '금속재기타울타리-알루미늄 900H', '금속재기타울타리', '900x2000mm', 'QT-2025-MF010', '금속재기타울타리-알루미늄 900H 시리즈');

-- 창살형울타리 모델
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'SPINDLE_FENCE_001', '창살형울타리-수직창살 1000H', '창살형울타리', '1000x2000mm', 'QT-2025-SF001', '창살형울타리-수직창살 1000H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'SPINDLE_FENCE_002', '창살형울타리-x자형 1200H', '창살형울타리', '1200x2000mm', 'QT-2025-SF002', '창살형울타리-x자형 1200H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'SPINDLE_FENCE_003', '창살형울타리-다이아몬드 1000H', '창살형울타리', '1000x2000mm', 'QT-2025-SF003', '창살형울타리-다이아몬드 1000H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'SPINDLE_FENCE_004', '창살형울타리-원형봉 1100H', '창살형울타리', '1100x2000mm', 'QT-2025-SF004', '창살형울타리-원형봉 1100H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'SPINDLE_FENCE_005', '창살형울타리-각형봉 1050H', '창살형울타리', '1050x2000mm', 'QT-2025-SF005', '창살형울타리-각형봉 1050H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'SPINDLE_FENCE_006', '창살형울타리-경사창살 1000H', '창살형울타리', '1000x2000mm', 'QT-2025-SF006', '창살형울타리-경사창살 1000H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'SPINDLE_FENCE_007', '창살형울타리-조밀창살 1150H', '창살형울타리', '1150x2000mm', 'QT-2025-SF007', '창살형울타리-조밀창살 1150H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'SPINDLE_FENCE_008', '창살형울타리-성글창살 1000H', '창살형울타리', '1000x2000mm', 'QT-2025-SF008', '창살형울타리-성글창살 1000H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'SPINDLE_FENCE_009', '창살형울타리-계단형 1200H', '창살형울타리', '1200x2000mm', 'QT-2025-SF009', '창살형울타리-계단형 1200H 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'SPINDLE_FENCE_010', '창살형울타리-물결형 900H', '창살형울타리', '900x2000mm', 'QT-2025-SF010', '창살형울타리-물결형 900H 시리즈');

-- 차양 모델
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'AWNING_001', '차양-수동 알루미늄 2000W', '차양', '2000x1500mm', 'QT-2025-AW001', '차양-수동 알루미늄 2000W 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'AWNING_002', '차양-반자동 스틸 2500W', '차양', '2500x1500mm', 'QT-2025-AW002', '차양-반자동 스틸 2500W 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'AWNING_003', '차양-전동 프리미엄 3000W', '차양', '3000x1500mm', 'QT-2025-AW003', '차양-전동 프리미엄 3000W 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'AWNING_004', '차양-카세트형 2000W', '차양', '2000x1200mm', 'QT-2025-AW004', '차양-카세트형 2000W 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'AWNING_005', '차양-반투명캔버스 2200W', '차양', '2200x1500mm', 'QT-2025-AW005', '차양-반투명캔버스 2200W 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'AWNING_006', '차양-방수천 2400W', '차양', '2400x1500mm', 'QT-2025-AW006', '차양-방수천 2400W 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'AWNING_007', '차양-방풍형 2000W', '차양', '2000x1500mm', 'QT-2025-AW007', '차양-방풍형 2000W 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'AWNING_008', '차양-LED조명 2500W', '차양', '2500x1500mm', 'QT-2025-AW008', '차양-LED조명 2500W 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'AWNING_009', '차양-태양광 3000W', '차양', '3000x1500mm', 'QT-2025-AW009', '차양-태양광 3000W 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'AWNING_010', '차양-리모콘식 2200W', '차양', '2200x1500mm', 'QT-2025-AW010', '차양-리모콘식 2200W 시리즈');

-- 자전거보관대 모델
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'BIKE_RACK_001', '자전거보관대-벽부착형 2대용', '자전거보관대', '600x400x200mm', 'QT-2025-BR001', '자전거보관대-벽부착형 2대용 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'BIKE_RACK_002', '자전거보관대-스탠드형 4대용', '자전거보관대', '1200x400x400mm', 'QT-2025-BR002', '자전거보관대-스탠드형 4대용 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'BIKE_RACK_003', '자전거보관대-수평거치 3대용', '자전거보관대', '900x400x300mm', 'QT-2025-BR003', '자전거보관대-수평거치 3대용 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'BIKE_RACK_004', '자전거보관대-라운드형 6대용', '자전거보관대', '1500x500x500mm', 'QT-2025-BR004', '자전거보관대-라운드형 6대용 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'BIKE_RACK_005', '자전거보관대-접이식 2대용', '자전거보관대', '500x300x150mm', 'QT-2025-BR005', '자전거보관대-접이식 2대용 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'BIKE_RACK_006', '자전거보관대-타워형 8대용', '자전거보관대', '1200x600x800mm', 'QT-2025-BR006', '자전거보관대-타워형 8대용 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'BIKE_RACK_007', '자전거보관대-잠금함일체형 2대', '자전거보관대', '700x400x250mm', 'QT-2025-BR007', '자전거보관대-잠금함일체형 2대 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'BIKE_RACK_008', '자전거보관대-슬랫형 5대용', '자전거보관대', '1000x300x400mm', 'QT-2025-BR008', '자전거보관대-슬랫형 5대용 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'BIKE_RACK_009', '자전거보관대-개별칸막이 4대', '자전거보관대', '800x400x450mm', 'QT-2025-BR009', '자전거보관대-개별칸막이 4대 시리즈');
INSERT INTO ptop.models (tenant_id, model_id, model_name, category, model_standard, quote_number, description) VALUES ('demo', 'BIKE_RACK_010', '자전거보관대-우산겸용 3대용', '자전거보관대', '900x400x250mm', 'QT-2025-BR010', '자전거보관대-우산겸용 3대용 시리즈');

-- 5. BOM (Bill of Materials) 삽입
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_001', '디자인형울타리-기본형 1000H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_001', '디자인형울타리-기본형 1000H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_001', '디자인형울타리-기본형 1000H', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_001', '디자인형울타리-기본형 1000H', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_002', '디자인형울타리-라운드톱 1200H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_002', '디자인형울타리-라운드톱 1200H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_002', '디자인형울타리-라운드톱 1200H', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_002', '디자인형울타리-라운드톱 1200H', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_003', '디자인형울타리-모던형 1000H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_003', '디자인형울타리-모던형 1000H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_003', '디자인형울타리-모던형 1000H', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_003', '디자인형울타리-모던형 1000H', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_004', '디자인형울타리-곡선형 1100H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_004', '디자인형울타리-곡선형 1100H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_004', '디자인형울타리-곡선형 1100H', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_004', '디자인형울타리-곡선형 1100H', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_005', '디자인형울타리-기하학형 1050H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_005', '디자인형울타리-기하학형 1050H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_005', '디자인형울타리-기하학형 1050H', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_005', '디자인형울타리-기하학형 1050H', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_006', '디자인형울타리-스트라이프 1000H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_006', '디자인형울타리-스트라이프 1000H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_006', '디자인형울타리-스트라이프 1000H', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_006', '디자인형울타리-스트라이프 1000H', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_007', '디자인형울타리-대각선 1150H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_007', '디자인형울타리-대각선 1150H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_007', '디자인형울타리-대각선 1150H', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_007', '디자인형울타리-대각선 1150H', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_008', '디자인형울타리-프레임형 1000H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_008', '디자인형울타리-프레임형 1000H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_008', '디자인형울타리-프레임형 1000H', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_008', '디자인형울타리-프레임형 1000H', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_009', '디자인형울타리-나무결 1200H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_009', '디자인형울타리-나무결 1200H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_009', '디자인형울타리-나무결 1200H', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_009', '디자인형울타리-나무결 1200H', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_010', '디자인형울타리-미니멀 900H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_010', '디자인형울타리-미니멀 900H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_010', '디자인형울타리-미니멀 900H', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'DESIGN_FENCE_010', '디자인형울타리-미니멀 900H', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_001', '금속재기타울타리-앵글형 1000H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_001', '금속재기타울타리-앵글형 1000H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_001', '금속재기타울타리-앵글형 1000H', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_001', '금속재기타울타리-앵글형 1000H', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_002', '금속재기타울타리-파이프형 1200H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_002', '금속재기타울타리-파이프형 1200H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_002', '금속재기타울타리-파이프형 1200H', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_002', '금속재기타울타리-파이프형 1200H', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_003', '금속재기타울타리-체인링크 1000H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_003', '금속재기타울타리-체인링크 1000H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_003', '금속재기타울타리-체인링크 1000H', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_003', '금속재기타울타리-체인링크 1000H', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_004', '금속재기타울타리-메쉬형 1100H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_004', '금속재기타울타리-메쉬형 1100H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_004', '금속재기타울타리-메쉬형 1100H', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_004', '금속재기타울타리-메쉬형 1100H', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_005', '금속재기타울타리-박스빔 1150H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_005', '금속재기타울타리-박스빔 1150H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_005', '금속재기타울타리-박스빔 1150H', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_005', '금속재기타울타리-박스빔 1150H', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_006', '금속재기타울타리-철봉격자 1050H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_006', '금속재기타울타리-철봉격자 1050H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_006', '금속재기타울타리-철봉격자 1050H', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_006', '금속재기타울타리-철봉격자 1050H', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_007', '금속재기타울타리-스틸플레이트 1000H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_007', '금속재기타울타리-스틸플레이트 1000H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_007', '금속재기타울타리-스틸플레이트 1000H', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_007', '금속재기타울타리-스틸플레이트 1000H', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_008', '금속재기타울타리-구조강재 1200H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_008', '금속재기타울타리-구조강재 1200H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_008', '금속재기타울타리-구조강재 1200H', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_008', '금속재기타울타리-구조강재 1200H', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_009', '금속재기타울타리-갈바강판 1100H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_009', '금속재기타울타리-갈바강판 1100H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_009', '금속재기타울타리-갈바강판 1100H', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_009', '금속재기타울타리-갈바강판 1100H', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_010', '금속재기타울타리-알루미늄 900H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_010', '금속재기타울타리-알루미늄 900H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_010', '금속재기타울타리-알루미늄 900H', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'METAL_FENCE_010', '금속재기타울타리-알루미늄 900H', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_001', '창살형울타리-수직창살 1000H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_001', '창살형울타리-수직창살 1000H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_001', '창살형울타리-수직창살 1000H', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_001', '창살형울타리-수직창살 1000H', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_002', '창살형울타리-x자형 1200H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_002', '창살형울타리-x자형 1200H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_002', '창살형울타리-x자형 1200H', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_002', '창살형울타리-x자형 1200H', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_003', '창살형울타리-다이아몬드 1000H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_003', '창살형울타리-다이아몬드 1000H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_003', '창살형울타리-다이아몬드 1000H', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_003', '창살형울타리-다이아몬드 1000H', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_004', '창살형울타리-원형봉 1100H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_004', '창살형울타리-원형봉 1100H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_004', '창살형울타리-원형봉 1100H', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_004', '창살형울타리-원형봉 1100H', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_005', '창살형울타리-각형봉 1050H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_005', '창살형울타리-각형봉 1050H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_005', '창살형울타리-각형봉 1050H', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_005', '창살형울타리-각형봉 1050H', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_006', '창살형울타리-경사창살 1000H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_006', '창살형울타리-경사창살 1000H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_006', '창살형울타리-경사창살 1000H', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_006', '창살형울타리-경사창살 1000H', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_007', '창살형울타리-조밀창살 1150H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_007', '창살형울타리-조밀창살 1150H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_007', '창살형울타리-조밀창살 1150H', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_007', '창살형울타리-조밀창살 1150H', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_008', '창살형울타리-성글창살 1000H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_008', '창살형울타리-성글창살 1000H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_008', '창살형울타리-성글창살 1000H', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_008', '창살형울타리-성글창살 1000H', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_009', '창살형울타리-계단형 1200H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_009', '창살형울타리-계단형 1200H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_009', '창살형울타리-계단형 1200H', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_009', '창살형울타리-계단형 1200H', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_010', '창살형울타리-물결형 900H', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_010', '창살형울타리-물결형 900H', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_010', '창살형울타리-물결형 900H', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'SPINDLE_FENCE_010', '창살형울타리-물결형 900H', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'AWNING_001', '차양-수동 알루미늄 2000W', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'AWNING_001', '차양-수동 알루미늄 2000W', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'AWNING_001', '차양-수동 알루미늄 2000W', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'AWNING_001', '차양-수동 알루미늄 2000W', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'AWNING_002', '차양-반자동 스틸 2500W', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'AWNING_002', '차양-반자동 스틸 2500W', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'AWNING_002', '차양-반자동 스틸 2500W', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'AWNING_002', '차양-반자동 스틸 2500W', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'AWNING_003', '차양-전동 프리미엄 3000W', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'AWNING_003', '차양-전동 프리미엄 3000W', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'AWNING_003', '차양-전동 프리미엄 3000W', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'AWNING_003', '차양-전동 프리미엄 3000W', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'AWNING_004', '차양-카세트형 2000W', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'AWNING_004', '차양-카세트형 2000W', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'AWNING_004', '차양-카세트형 2000W', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'AWNING_004', '차양-카세트형 2000W', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'AWNING_005', '차양-반투명캔버스 2200W', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'AWNING_005', '차양-반투명캔버스 2200W', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'AWNING_005', '차양-반투명캔버스 2200W', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'AWNING_005', '차양-반투명캔버스 2200W', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'AWNING_006', '차양-방수천 2400W', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'AWNING_006', '차양-방수천 2400W', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'AWNING_006', '차양-방수천 2400W', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'AWNING_006', '차양-방수천 2400W', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'AWNING_007', '차양-방풍형 2000W', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'AWNING_007', '차양-방풍형 2000W', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'AWNING_007', '차양-방풍형 2000W', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'AWNING_007', '차양-방풍형 2000W', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'AWNING_008', '차양-LED조명 2500W', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'AWNING_008', '차양-LED조명 2500W', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'AWNING_008', '차양-LED조명 2500W', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'AWNING_008', '차양-LED조명 2500W', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'AWNING_009', '차양-태양광 3000W', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'AWNING_009', '차양-태양광 3000W', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'AWNING_009', '차양-태양광 3000W', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'AWNING_009', '차양-태양광 3000W', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'AWNING_010', '차양-리모콘식 2200W', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'AWNING_010', '차양-리모콘식 2200W', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'AWNING_010', '차양-리모콘식 2200W', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'AWNING_010', '차양-리모콘식 2200W', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_001', '자전거보관대-벽부착형 2대용', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_001', '자전거보관대-벽부착형 2대용', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_001', '자전거보관대-벽부착형 2대용', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_001', '자전거보관대-벽부착형 2대용', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_002', '자전거보관대-스탠드형 4대용', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_002', '자전거보관대-스탠드형 4대용', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_002', '자전거보관대-스탠드형 4대용', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_002', '자전거보관대-스탠드형 4대용', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_003', '자전거보관대-수평거치 3대용', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_003', '자전거보관대-수평거치 3대용', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_003', '자전거보관대-수평거치 3대용', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_003', '자전거보관대-수평거치 3대용', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_004', '자전거보관대-라운드형 6대용', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_004', '자전거보관대-라운드형 6대용', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_004', '자전거보관대-라운드형 6대용', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_004', '자전거보관대-라운드형 6대용', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_005', '자전거보관대-접이식 2대용', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_005', '자전거보관대-접이식 2대용', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_005', '자전거보관대-접이식 2대용', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_005', '자전거보관대-접이식 2대용', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_006', '자전거보관대-타워형 8대용', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_006', '자전거보관대-타워형 8대용', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_006', '자전거보관대-타워형 8대용', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_006', '자전거보관대-타워형 8대용', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_007', '자전거보관대-잠금함일체형 2대', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_007', '자전거보관대-잠금함일체형 2대', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_007', '자전거보관대-잠금함일체형 2대', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_007', '자전거보관대-잠금함일체형 2대', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_008', '자전거보관대-슬랫형 5대용', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_008', '자전거보관대-슬랫형 5대용', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_008', '자전거보관대-슬랫형 5대용', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_008', '자전거보관대-슬랫형 5대용', '페인트', 1, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_009', '자전거보관대-개별칸막이 4대', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_009', '자전거보관대-개별칸막이 4대', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_009', '자전거보관대-개별칸막이 4대', '용접', 2, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_009', '자전거보관대-개별칸막이 4대', '페인트', 2, 'L', 15000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_010', '자전거보관대-우산겸용 3대용', 'MM-PIPE-50', 'HGI PIPE 50mm', '50x50x1.6', 2, 'EA', 45000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_id, material_name, standard, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_010', '자전거보관대-우산겸용 3대용', 'MM-PIPE-75', 'HGI PIPE 75mm', '75x75x2.3', 3, 'EA', 68000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_010', '자전거보관대-우산겸용 3대용', '용접', 1, 'EA', 5000);
INSERT INTO ptop.bom (tenant_id, model_id, model_name, material_name, quantity, unit, unit_price) VALUES ('demo', 'BIKE_RACK_010', '자전거보관대-우산겸용 3대용', '페인트', 1, 'L', 15000);

-- 6. 가격 책정 (Pricing) 삽입
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 1, '디자인형울타리', '디자인형울타리-기본형 1000H', '1000x2000mm', 'm', 550000, 'QT-2025-DF001');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 2, '디자인형울타리', '디자인형울타리-라운드톱 1200H', '1200x2000mm', 'm', 600000, 'QT-2025-DF002');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 3, '디자인형울타리', '디자인형울타리-모던형 1000H', '1000x2000mm', 'm', 650000, 'QT-2025-DF003');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 4, '디자인형울타리', '디자인형울타리-곡선형 1100H', '1100x2000mm', 'm', 700000, 'QT-2025-DF004');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 5, '디자인형울타리', '디자인형울타리-기하학형 1050H', '1050x2000mm', 'm', 750000, 'QT-2025-DF005');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 6, '디자인형울타리', '디자인형울타리-스트라이프 1000H', '1000x2000mm', 'm', 800000, 'QT-2025-DF006');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 7, '디자인형울타리', '디자인형울타리-대각선 1150H', '1150x2000mm', 'm', 850000, 'QT-2025-DF007');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 8, '디자인형울타리', '디자인형울타리-프레임형 1000H', '1000x2000mm', 'm', 900000, 'QT-2025-DF008');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 9, '디자인형울타리', '디자인형울타리-나무결 1200H', '1200x2000mm', 'm', 950000, 'QT-2025-DF009');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 10, '디자인형울타리', '디자인형울타리-미니멀 900H', '900x2000mm', 'm', 1000000, 'QT-2025-DF010');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 11, '금속재기타울타리', '금속재기타울타리-앵글형 1000H', '1000x2000mm', 'm', 1050000, 'QT-2025-MF001');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 12, '금속재기타울타리', '금속재기타울타리-파이프형 1200H', '1200x2000mm', 'm', 1100000, 'QT-2025-MF002');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 13, '금속재기타울타리', '금속재기타울타리-체인링크 1000H', '1000x2000mm', 'm', 1150000, 'QT-2025-MF003');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 14, '금속재기타울타리', '금속재기타울타리-메쉬형 1100H', '1100x2000mm', 'm', 1200000, 'QT-2025-MF004');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 15, '금속재기타울타리', '금속재기타울타리-박스빔 1150H', '1150x2000mm', 'm', 1250000, 'QT-2025-MF005');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 16, '금속재기타울타리', '금속재기타울타리-철봉격자 1050H', '1050x2000mm', 'm', 1300000, 'QT-2025-MF006');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 17, '금속재기타울타리', '금속재기타울타리-스틸플레이트 1000H', '1000x2000mm', 'm', 1350000, 'QT-2025-MF007');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 18, '금속재기타울타리', '금속재기타울타리-구조강재 1200H', '1200x2000mm', 'm', 1400000, 'QT-2025-MF008');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 19, '금속재기타울타리', '금속재기타울타리-갈바강판 1100H', '1100x2000mm', 'm', 1450000, 'QT-2025-MF009');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 20, '금속재기타울타리', '금속재기타울타리-알루미늄 900H', '900x2000mm', 'm', 1500000, 'QT-2025-MF010');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 21, '창살형울타리', '창살형울타리-수직창살 1000H', '1000x2000mm', 'm', 1550000, 'QT-2025-SF001');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 22, '창살형울타리', '창살형울타리-x자형 1200H', '1200x2000mm', 'm', 1600000, 'QT-2025-SF002');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 23, '창살형울타리', '창살형울타리-다이아몬드 1000H', '1000x2000mm', 'm', 1650000, 'QT-2025-SF003');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 24, '창살형울타리', '창살형울타리-원형봉 1100H', '1100x2000mm', 'm', 1700000, 'QT-2025-SF004');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 25, '창살형울타리', '창살형울타리-각형봉 1050H', '1050x2000mm', 'm', 1750000, 'QT-2025-SF005');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 26, '창살형울타리', '창살형울타리-경사창살 1000H', '1000x2000mm', 'm', 1800000, 'QT-2025-SF006');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 27, '창살형울타리', '창살형울타리-조밀창살 1150H', '1150x2000mm', 'm', 1850000, 'QT-2025-SF007');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 28, '창살형울타리', '창살형울타리-성글창살 1000H', '1000x2000mm', 'm', 1900000, 'QT-2025-SF008');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 29, '창살형울타리', '창살형울타리-계단형 1200H', '1200x2000mm', 'm', 1950000, 'QT-2025-SF009');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 30, '창살형울타리', '창살형울타리-물결형 900H', '900x2000mm', 'm', 2000000, 'QT-2025-SF010');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 31, '차양', '차양-수동 알루미늄 2000W', '2000x1500mm', 'm', 2050000, 'QT-2025-AW001');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 32, '차양', '차양-반자동 스틸 2500W', '2500x1500mm', 'm', 2100000, 'QT-2025-AW002');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 33, '차양', '차양-전동 프리미엄 3000W', '3000x1500mm', 'm', 2150000, 'QT-2025-AW003');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 34, '차양', '차양-카세트형 2000W', '2000x1200mm', 'm', 2200000, 'QT-2025-AW004');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 35, '차양', '차양-반투명캔버스 2200W', '2200x1500mm', 'm', 2250000, 'QT-2025-AW005');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 36, '차양', '차양-방수천 2400W', '2400x1500mm', 'm', 2300000, 'QT-2025-AW006');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 37, '차양', '차양-방풍형 2000W', '2000x1500mm', 'm', 2350000, 'QT-2025-AW007');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 38, '차양', '차양-LED조명 2500W', '2500x1500mm', 'm', 2400000, 'QT-2025-AW008');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 39, '차양', '차양-태양광 3000W', '3000x1500mm', 'm', 2450000, 'QT-2025-AW009');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 40, '차양', '차양-리모콘식 2200W', '2200x1500mm', 'm', 2500000, 'QT-2025-AW010');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 41, '자전거보관대', '자전거보관대-벽부착형 2대용', '600x400x200mm', 'm', 2550000, 'QT-2025-BR001');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 42, '자전거보관대', '자전거보관대-스탠드형 4대용', '1200x400x400mm', 'm', 2600000, 'QT-2025-BR002');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 43, '자전거보관대', '자전거보관대-수평거치 3대용', '900x400x300mm', 'm', 2650000, 'QT-2025-BR003');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 44, '자전거보관대', '자전거보관대-라운드형 6대용', '1500x500x500mm', 'm', 2700000, 'QT-2025-BR004');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 45, '자전거보관대', '자전거보관대-접이식 2대용', '500x300x150mm', 'm', 2750000, 'QT-2025-BR005');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 46, '자전거보관대', '자전거보관대-타워형 8대용', '1200x600x800mm', 'm', 2800000, 'QT-2025-BR006');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 47, '자전거보관대', '자전거보관대-잠금함일체형 2대', '700x400x250mm', 'm', 2850000, 'QT-2025-BR007');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 48, '자전거보관대', '자전거보관대-슬랫형 5대용', '1000x300x400mm', 'm', 2900000, 'QT-2025-BR008');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 49, '자전거보관대', '자전거보관대-개별칸막이 4대', '800x400x450mm', 'm', 2950000, 'QT-2025-BR009');
INSERT INTO ptop.pricing (tenant_id, no, product_type, model_name, standard, unit, unit_price, quote_number) VALUES ('demo', 50, '자전거보관대', '자전거보관대-우산겸용 3대용', '900x400x250mm', 'm', 3000000, 'QT-2025-BR010');
