-- Phase 3 P1: Core tables for Quotations, Purchase Orders, Inventory, and Audit
-- Note: Add RLS policies separately per tenant_id; this script only creates structures and indexes.

-- 1) Quotations
CREATE TABLE IF NOT EXISTS quotations (
  quotation_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  customer_id TEXT,
  project_id TEXT,
  version INT DEFAULT 1,
  status TEXT DEFAULT 'draft',
  total_amount NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_quotations_tenant_created ON quotations(tenant_id, created_at DESC);

CREATE TABLE IF NOT EXISTS quotation_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quotation_id TEXT NOT NULL REFERENCES quotations(quotation_id) ON DELETE CASCADE,
  item_name TEXT,
  spec TEXT,
  quantity NUMERIC DEFAULT 0,
  unit_price NUMERIC DEFAULT 0,
  total NUMERIC GENERATED ALWAYS AS (quantity * unit_price) STORED
);
CREATE INDEX IF NOT EXISTS idx_quotation_items_q ON quotation_items(quotation_id);

-- 2) Purchase Orders
CREATE TABLE IF NOT EXISTS purchase_orders (
  po_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  vendor_id TEXT,
  project_id TEXT,
  status TEXT DEFAULT 'draft',
  due_date DATE,
  quotation_ref TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_po_tenant_created ON purchase_orders(tenant_id, created_at DESC);

CREATE TABLE IF NOT EXISTS po_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_id TEXT NOT NULL REFERENCES purchase_orders(po_id) ON DELETE CASCADE,
  material_id TEXT,
  item_name TEXT,
  quantity NUMERIC DEFAULT 0,
  unit_price NUMERIC DEFAULT 0,
  total NUMERIC GENERATED ALWAYS AS (quantity * unit_price) STORED
);
CREATE INDEX IF NOT EXISTS idx_po_items_po ON po_items(po_id);

-- 3) Inventory
CREATE TABLE IF NOT EXISTS inventory (
  tenant_id TEXT NOT NULL,
  material_id TEXT NOT NULL,
  qty_on_hand NUMERIC DEFAULT 0,
  qty_reserved NUMERIC DEFAULT 0,
  location TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (tenant_id, material_id)
);

CREATE TABLE IF NOT EXISTS inventory_txns (
  txn_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  material_id TEXT NOT NULL,
  delta NUMERIC NOT NULL,
  reason TEXT,
  related_po_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_inv_txn_tenant_material ON inventory_txns(tenant_id, material_id, created_at DESC);

-- 4) Audit log
CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts TIMESTAMPTZ DEFAULT NOW(),
  actor TEXT,
  tenant_id TEXT,
  entity_type TEXT,
  entity_id TEXT,
  action TEXT,
  before_json JSONB,
  after_json JSONB
);
CREATE INDEX IF NOT EXISTS idx_audit_tenant_ts ON audit_log(tenant_id, ts DESC);

