-- Phase 3: BOM snapshots to persist source structures at creation time

CREATE TABLE IF NOT EXISTS bom_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  linked_type TEXT NOT NULL, -- 'quotation' | 'project' | 'po'
  linked_id TEXT NOT NULL,
  revision INT DEFAULT 1,
  payload_json JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bom_snapshots_link ON bom_snapshots(tenant_id, linked_type, linked_id, created_at DESC);

